### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by petrovskaia** [konstantinklemmer/pe-gnn#1]
Thank you for your interesting paper!

I attempted to run your code, but unfortunately, an error occurred with the message "AttributeError: 'NoneType' object has no attribute 'knn_graph'". I have already checked the loading of the datasets, it completes correctly. 

Maybe you have an idea how to fix this error?

**Comment by KeunJuSong** [comment]
Hi, I had the same problem and solved it. If your error came out in Colab, this way may be simple to solve it.

I found that torch and cuda version in Colab is currently 2.0.0 and 11.8. 
This means that 'torch-scatter, torch-sparse, torch-cluster, and torch-spline-conv' are not installed because of the version mismatch. 

Therefore, you need to change the code of pip install for torch to match the version like this:

`
! pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-2.0.0+cu118.html
`
`
! pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-2.0.0+cu118.html
`
`
! pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-2.0.0+cu118.html
`
`
! pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.0.0+cu118.html
`

**Comment by konstantinklemmer** [comment]
Hi both and sorry for the late reply - I didn't get a notification on this weirdly. Seems like this is resolved but please open an new issue if something else comes up.
